### ISSUE TITLE
Couldn't download the Interactive Map to PDF

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/DRR-datacenter#1]
When I try to to download the interactive map with the dashboard, it returns [Object Object]

Link : http://asdc.immap.org/maps/5568/view

<img width="493" alt="Screen Shot 2021-12-10 at 10 54 04" src="https://user-images.githubusercontent.com/28089698/145519483-4080169a-9dc3-4297-85f8-a3e9cc069e7b.png">

Kindly identify the issue and fix

**Comment by sud0su** [comment]
hi @rafinkanisa ,
the map can't be downloaded, it happened not because of a code error but because there are two layers (gfs-msl-pressure & metar) from ogcie.iblsoft.com that don't have map legend graphics. 
i have been discussed with @dodiws , and we think the best option we can do is just two options :
1. unselect the layers (gfs-msl-pressure & metar) before print
2. make a contact with ogcie.iblsoft.com and ask why the layers (gfs-msl-pressure & metar) did not have a legend

**Comment by rafinkanisa** [comment]
Can't we show more useful error message like saying, please unselect the layer?

**Comment by sud0su** [comment]
> Can't we show more useful error message like saying, please unselect the layer?

I will try to dev and do a test on my local machine first to make sure is it possible or not, because the update code will be affected to all interactive map

**Comment by rafinkanisa** [comment]
alright. I'll be waiting for the updates then

**Comment by sud0su** [comment]
> alright. I'll be waiting for the updates then

still can't display the popup message to uncheck the specific layers(the error layer), this bug needs more time to debug and develop because these changes will have an impact on all print processes in the interactive map.

**Comment by dodiws** [comment]
[this commit](https://github.com/iMMAP/DRR-datacenter/commit/e95f353e144894eb8a9ddf13823d75602137cf1d) show error message with workaround suggestions when print fail on interactive map because of GetLegendGraphic error

<img width="576" alt="error message with workaround suggestions" src="https://user-images.githubusercontent.com/23377236/149471843-13a397bb-f982-4712-8f63-1880fa4bbc2b.png">
