### ISSUE TITLE
Update Earthquake Data

### ISSUE THREAD

**Issue by rafinkanisa** [iMMAP/DRR-datacenter#15]
As part of re-activating the ASDC to humanitarian organization, we'll have to update all of the outdated data in ASDC to the most recent one

TODO :

- [x] Create Script to update the earthquake data
- [x] Perform earthquake data update

**Comment by dodiws** [comment]
This [commit](https://github.com/iMMAP/DRR-datacenter/commit/6f0dcf27a8790770e7505b8a5ce41191a59af9be) modifies `getLatestEarthQuake` and `getLatestShakemap` function to support date range filter using `startdate` and `enddate` parameters. With date range filter, API call can be divided into several call to reduce load because the required data update periode is long.

The earthquake data then can be updated with function call (modify `startdate` and `enddate` as necessary):
```python
getLatestEarthQuake(startdate=datetime.datetime(2021,7,1),enddate=datetime.datetime(2021,12,1))

getLatestShakemap(includeShakeMap=True,startdate=datetime.datetime(2021,7,1),enddate=datetime.datetime(2021,12,1))
```

**Comment by dodiws** [comment]
Error on earthquake `event_code=7000f950` shakemap update:
```
>>> getLatestShakemap(includeShakeMap=True,startdate=datetime.datetime(2021,9,8),enddate=datetime.datetime(2021,9,9))
GEOS error: TopologyException: Input geom 1 is invalid: Self-intersection at or near point 75.375 36.499999000000003 at 75.375 36.499999000000003
Saved: earthquake_shakemap object
Ignoring Feature ID 1 because: Could not retrieve geometry from feature.
Saved: earthquake_shakemap object
Saved: earthquake_shakemap object
Saved: earthquake_shakemap object
----- Process baseline historical Statistics for EarthQuake------

earthqueke id 7000f950 modified
```
Feature ID 1 has Self-intersection on its geometry. Feature ID 1 is geometry of shakemap area on Mercalli Intensity Scale level 2 (weak). Level 1, 3, 4, 5 are normal. This makes shakemap area on Mercalli Intensity Scale level 2 data not appear on map or [its earthquake dashboard](http://asdc.immap.org/dashboard/?page=earthquake&eq_event=7000f950) calculation for this earthquake event.

Solutions alternatives:

- fix Self-intersection problem on Feature ID 1 geometry
- let the data as is because it is the original data from USGS

**Comment by dodiws** [comment]
Excluding earthquake (event_code=7000f950) shakemap above, earthquake data has been updated, and the update script scheduled to run periodically as celery task.
